[server]
port = 8501
address = "0.0.0.0"

[browser]
serverAddress = "localhost"
serverPort = 8501

[runner]
fastRerun = true

[theme]
base = "light"
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"
